name: 'Deploy B2C Policy Files'
inputs:
  B2C_TENANTID:
    required: true
  B2C_TENANTOBJECTID:
    required: true
  B2C_HOSTNAME:
    required: true
  B2C_DEPLOYMENTMODE:
    required: true
  B2C_EXTENSIONAPP_CLIENTID:
    required: true
  B2C_EXTENSIONAPP_OBJECTID:
    required: true
  API_HOST_URL:
    required: true
  B2C_APPLE_CLIENTID:
    required: true
  B2C_APPLE_CLIENTSECRET:
    required: true
  B2C_GOOGLE_CLIENTID:
    required: true
  B2C_GOOGLE_CLIENTSECRET:
    required: true
  B2C_MICROSOFT_CLIENTID:
    required: true
  B2C_MICROSOFT_CLIENTSECRET:
    required: true
  B2C_APPINSIGHTS_INSTRUMENTATIONKEY:
    required: true
  B2C_APPINSIGHTS_DEVELOPERMODE:
    required: true
  B2C_ID_TOKEN_HINT_AUDIENCE:
    required: true
  B2C_ID_TOKEN_HINT_CERT:
    required: true
  B2C_PROXY_IEF_CLIENTID:
    required: true
  B2C_IEF_CLIENTID:
    required: true
  B2C_DEPLOY_CLIENTID:
    required: true
  B2C_DEPLOY_CLIENTSECRET:
    required: true
runs:
  using: "composite"
  steps: 
    - name: 'Prepare policy files'
      shell: 'pwsh'
      working-directory: 'src/b2c'
      env:
        B2C_TENANTID: ${{ inputs.B2C_TENANTID }}
        B2C_TENANTOBJECTID: ${{ inputs.B2C_TENANTOBJECTID }}
        B2C_HOSTNAME: ${{ inputs.B2C_HOSTNAME }}
        B2C_DEPLOYMENTMODE: ${{ inputs.B2C_DEPLOYMENTMODE }}
        B2C_EXTENSIONAPP_CLIENTID: ${{ inputs.B2C_EXTENSIONAPP_CLIENTID }}
        B2C_EXTENSIONAPP_OBJECTID: ${{ inputs.B2C_EXTENSIONAPP_OBJECTID }}
        API_HOST_URL: ${{ inputs.API_HOST_URL }}
        B2C_APPLE_CLIENTID: ${{ inputs.B2C_APPLE_CLIENTID }}
        B2C_APPLE_CLIENTSECRET: ${{ inputs.B2C_APPLE_CLIENTSECRET }}
        B2C_GOOGLE_CLIENTID: ${{ inputs.B2C_GOOGLE_CLIENTID }}
        B2C_GOOGLE_CLIENTSECRET: ${{ inputs.B2C_GOOGLE_CLIENTSECRET }}
        B2C_MICROSOFT_CLIENTID: ${{ inputs.B2C_MICROSOFT_CLIENTID }}
        B2C_MICROSOFT_CLIENTSECRET: ${{ inputs.B2C_MICROSOFT_CLIENTSECRET }}
        B2C_APPINSIGHTS_INSTRUMENTATIONKEY: ${{ inputs.B2C_APPINSIGHTS_INSTRUMENTATIONKEY }}
        B2C_APPINSIGHTS_DEVELOPERMODE: ${{ inputs.B2C_APPINSIGHTS_DEVELOPERMODE }}
        B2C_ID_TOKEN_HINT_AUDIENCE: ${{ inputs.B2C_ID_TOKEN_HINT_AUDIENCE }}
        B2C_ID_TOKEN_HINT_CERT: ${{ inputs.B2C_ID_TOKEN_HINT_CERT }}
        B2C_PROXY_IEF_CLIENTID: ${{ inputs.B2C_PROXY_IEF_CLIENTID }}
        B2C_IEF_CLIENTID: ${{ inputs.B2C_IEF_CLIENTID }}
      run: |
        .\Invoke-PrepareIEFPolicyFiles.ps1
    - name: 'Deploy policy files'
      shell: 'pwsh'
      working-directory: 'src/b2c'
      run: |
        .\Invoke-DeployIEFPolicyFile.ps1 -TenantId ${{ inputs.B2C_TENANTOBJECTID }} -ClientId ${{ inputs.B2C_DEPLOY_CLIENTID }} -ClientSecret ${{ inputs.B2C_DEPLOY_CLIENTSECRET }}